package com.lhu.vehicle_rent_backend.DTO;
// Generated Aug 15, 2020 8:20:18 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Book generated by hbm2java
 */
@Entity
//@Table(name = "book", catalog = "vehicle_rent")
public class Book implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String status;
	private String datetime;
	private String duration;
	private String days;
	private String pickUpPoint;
	private String pickOffPoint;
	private boolean isWithDriver;
	private String avgCost;
	
	@ManyToOne
	private User user = new User();
	
	@ManyToOne
	private Vehicle vehicle = new Vehicle();

	public int getBookingId() {
		return id;
	}

	public void setBookingId(int bookingId) {
		this.id = bookingId;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDatetime() {
		return datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getDays() {
		return days;
	}

	public void setDays(String days) {
		this.days = days;
	}

	public String getPickUpPoint() {
		return pickUpPoint;
	}

	public void setPickUpPoint(String pickUpPoint) {
		this.pickUpPoint = pickUpPoint;
	}

	public String getPickOffPoint() {
		return pickOffPoint;
	}

	public void setPickOffPoint(String pickOffPoint) {
		this.pickOffPoint = pickOffPoint;
	}

	public boolean isWithDriver() {
		return isWithDriver;
	}

	public void setWithDriver(boolean isWithDriver) {
		this.isWithDriver = isWithDriver;
	}

	public String getAvgCost() {
		return avgCost;
	}

	public void setAvgCost(String avgCost) {
		this.avgCost = avgCost;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Vehicle getVehicle() {
		return vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}


	@Override
	public String toString() {
		return "Book [id=" + id + ", status=" + status + ", datetime=" + datetime + ", duration=" + duration + ", days="
				+ days + ", pickUpPoint=" + pickUpPoint + ", pickOffPoint=" + pickOffPoint + ", isWithDriver="
				+ isWithDriver + ", avgCost=" + avgCost + "]";
	}

	public String to_String() {
		String userStr = user!=null?user.toString():"NULL";
		String vehicleStr = vehicle!=null?vehicle.toString():"NULL";
		
		return "Book [id=" + id + ", status=" + status + ", datetime=" + datetime + ", duration="
				+ duration + ", days=" + days + ", pickUpPoint=" + pickUpPoint + ", pickOffPoint=" + pickOffPoint
				+ ", isWithDriver=" + isWithDriver + ", avgCost=" + avgCost + ", user=" + userStr + ", vehicle=" + vehicleStr
				+ "]";
	}
	
	

	
}
