package com.lhu.vehicle_rent_backend.DTO;
// Generated Aug 15, 2020 8:20:18 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
//@Table(name = "book", catalog = "vehicle_rent")
public class Book implements java.io.Serializable {

	@Override
	public String toString() {
		return "Book [id=" + id + ", vid=" + vid + ", uid=" + uid + ", status=" + status + ", datetime=" + datetime
				+ ", pickupPoint=" + pickupPoint + "]";
	}
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private Integer vid;
	private Integer uid;
	private String status;
	private String datetime;
	private String pickupPoint;
	
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Integer getVid() {
		return vid;
	}
	public void setVid(Integer vid) {
		this.vid = vid;
	}
	public Integer getUid() {
		return uid;
	}
	public void setUid(Integer uid) {
		this.uid = uid;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getDatetime() {
		return datetime;
	}
	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}
	public String getPickupPoint() {
		return pickupPoint;
	}
	public void setPickupPoint(String pickupPoint) {
		this.pickupPoint = pickupPoint;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
}
