package com.lhu.vehicle_rent_backend.DTO;
// Generated Aug 15, 2020 8:20:18 PM by Hibernate Tools 4.3.1.Final

import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.NotBlank;
import org.springframework.web.multipart.MultipartFile;

/**
 * User generated by hbm2java
 */
@Entity
// @Table(name = "user", catalog = "vehicle_rent")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id = new Integer(0);
	@NotBlank(message = "Please enter the email")
	private String email = "";
	@NotBlank(message = "Please enter the password")
	private String password = "";
	@NotBlank(message = "Please enter the confirm password")
	private String tp = "";
	@NotBlank(message = "Please enter the role")
	private String role = "";
	@NotBlank(message = "Please enter the image")
	private String image = "";
	@NotBlank(message = "Please enter the status")
	private String status = "";

	@Transient
	private String confirmPassword = "";
	@Override
	public String toString() {
		return "User [id=" + id + ", email=" + email + ", password=" + password + ", tp=" + tp + ", role=" + role
				+ ", image=" + image + ", status=" + status + ", confirmPassword=" + confirmPassword + ", file=" + file
				+ "]";
	}

	@Transient
	private MultipartFile file;

	// default constructor
	public User() {

		this.image = "UIMG" + UUID.randomUUID().toString().substring(26).toUpperCase();

	}

	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTp() {
		return this.tp;
	}

	public void setTp(String tp) {
		this.tp = tp;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
